export const copyFAB = {
    sprint: "اسپرینت",
    backlog: "بک‌لاگ",
    placement: "محل قرارگیری",
    priority: "اهمیت",
    defaultPriority: "اهمیت پیش‌فرض",
    defaultSprint: "اسپرینت پیش‌فرض",
    assignee: "مسئول انجام",
    defaultAssignee: "مسئول پیش‌فرض",
    labels: "برچسب‌ها",
    defaultLabels: "برچسب‌های پیش‌فرض",
    type: "نوع تسک",
    summary: "عنوان",
    description: "توضیحات",
    epic: "اپیک",
    ref: "شناسه داخلی",
    addAttachment: "افزودن عکس یا فایل",
    attachmentHelp: "فایل‌ها بعد از ساخته‌شدن Issue در Jira آپلود می‌شوند و داخل JSON ذخیره نمی‌شوند.",
    attachmentDrop: "عکس یا فایل را اینجا رها کن، یا برای انتخاب کلیک کن",
    attachmentDropActive: "برای پیوست کردن رها کن",
    attachmentTypes: "PNG، JPG، WEBP، PDF، WEBM، TXT، LOG، JSON · حداکثر ۱۲ مگابایت برای هر فایل",
    richHelp: "فرمت Jira Wiki",
    createIssue: "ساخت تسک",
    addToBatch: "افزودن به گروه",
    createBatch: "ساخت در Jira",
    createSelected: "ساخت انتخاب‌شده‌ها",
    validate: "اعتبارسنجی",
    dryRun: "اجرای آزمایشی",
    reviewIssues: "مرور تسک‌ها",
    jsonEditor: "ویرایشگر JSON",
    rawJson: "JSON خام",
    jsonValid: "JSON معتبر است",
    jsonInvalid: "JSON نامعتبر است",
    sampleJson: "دانلود JSON نمونه",
    uploadJson: "آپلود JSON",
    aiTemplate: "کپی پرامپت AI",
    copied: "کپی شد",
    resetSample: "برگرداندن نمونه",
    searchIssues: "جستجو در تسک‌ها…",
    filter: "فیلتر",
    allTypes: "همه نوع‌ها",
    allPlacements: "همه محل‌ها",
    sprintOnly: "اسپرینت",
    backlogOnly: "بک‌لاگ",
    moveSelected: "انتقال انتخاب‌شده‌ها…",
    settings: "ظاهر و چیدمان",
    sidebarSettings: "تنظیمات",
    sidebarProjects: "پروژه‌ها",
    helpSupport: "راهنما و پشتیبانی",
    clearForm: "پاک کردن فرم",
    emptyLaneHint: "تسک‌هایی که به این بخش منتقل می‌کنی بلافاصله نمایش داده می‌شوند.",
    batchSettings: "تنظیمات گروهی",
    change: "تغییر",
    issueDetails: "جزئیات تسک",
    noIssueSelected: "برای ویرایش، یک تسک را انتخاب کن.",
    noIssues: "با این فیلتر تسکی پیدا نشد.",
    emptyLane: "تسکی در این ستون نیست",
    selected: "انتخاب‌شده",
    selectAll: "انتخاب همه",
    clearSelection: "پاک کردن انتخاب",
    sendBacklog: "فرستادن انتخاب‌شده‌ها به بک‌لاگ",
    duplicate: "کپی",
    delete: "حذف",
    inherited: "پیش‌فرض گروه",
    useDefault: "استفاده از پیش‌فرض گروه",
    noDefault: "بدون پیش‌فرض",
    noEpic: "بدون اپیک",
    active: "فعال",
    future: "آینده",
    projectSearch: "جستجوی پروژه…",
    projectEmpty: "پروژه‌ای پیدا نشد.",
    epicSearch: "جستجو بین اپیک‌های این گروه یا Jira…",
    epicEmpty: "اپیکی پیدا نشد.",
    batchEpic: "این گروه",
    jiraEpic: "Jira",
    labelSearch: "جستجو یا ساخت برچسب…",
    labelEmpty: "برچسبی پیدا نشد؛ نام را بنویس و Enter بزن تا ساخته شود.",
    loadingLabels: "در حال دریافت برچسب‌های Jira…",
    createLabel: "ساخت برچسب",
    assigneeSearch: "جستجوی کاربران قابل تخصیص…",
    assigneeEmpty: "کاربر قابل تخصیصی پیدا نشد.",
    unassigned: "بدون مسئول",
    importReady: "JSON آماده مرور است.",
    errors: "خطا",
    warnings: "هشدار",
    issues: "تسک",
    runResults: "نتیجه اجرا",
    retryFailed: "تلاش دوباره برای ساخت‌های ناموفق",
    retrySprint: "تلاش دوباره برای انتقال اسپرینت",
    created: "ساخته شد",
    failed: "ناموفق",
    attachmentsFailed: "آپلود پیوست ناموفق",
    noResults: "هنوز چیزی در Jira ساخته نشده.",
    confirmCreateTitle: "این تسک‌ها در Jira ساخته شوند؟",
    confirmCreateDescription: "فقط تسک‌های انتخاب‌شده ساخته می‌شوند و اپیک‌های محلی موردنیاز خودکار اضافه می‌شوند.",
    confirmCreate: "ساخت در Jira",
    cancel: "انصراف",
    theme: "تم",
    light: "روشن",
    dark: "تیره",
    system: "سیستم",
    language: "زبان",
    accent: "رنگ اصلی",
    layout: "چیدمان مرور",
    grid: "گرید",
    list: "لیست",
    boardView: "برد",
    columns: "تعداد ستون گرید",
    density: "تراکم",
    compact: "فشرده",
    comfortable: "متعادل",
    spacious: "باز",
    done: "تمام",
    context: "تنظیمات Jira",
    autoSprint: "اسپرینت فعال به‌صورت خودکار انتخاب شد.",
    noSprint: "اسپرینت فعال/آینده پیدا نشد؛ تسک‌ها تا زمان تغییر در بک‌لاگ می‌مانند.",
    quickSuccess: "تسک با موفقیت ساخته شد.",
    quickFailure: "ساخت تسک ناموفق بود.",
    imported: "وارد شد",
    downloadPrompt: "دانلود پرامپت AI",
    viewIssue: "مشاهده در Jira",
    createCount: "ساخت {count} تسک",
    workspace: "فضای کار",
    workspaceTitle: "فضای کار QueueMint",
    workspaceHint: "وضعیت بورد را یکجا ببین، سریع وارد کار شو و عملیات امن Jira را دوباره استفاده کن.",
    commandPalette: "فرمان سریع",
    commandPaletteHint: "بین بخش‌ها جابه‌جا شو یا یک عملیات ذخیره‌شده را اجرا کن.",
    commandSearch: "جستجوی فرمان، صفحه یا عملیات…",
    commandEmpty: "فرمانی پیدا نشد.",
    openCommandPalette: "باز کردن فرمان سریع",
    savedActions: "عملیات ذخیره‌شده",
    savedActionsHint: "یک تنظیم ویرایش گروهی را یک بار ذخیره کن و برای انتخاب‌های بعدی دوباره استفاده کن.",
    noSavedActions: "هنوز عملیاتی ذخیره نشده. یک ویرایش گروهی تنظیم کن و آن را ذخیره کن.",
    saveAction: "ذخیره به‌عنوان عملیات",
    actionName: "نام عملیات",
    actionNamePlaceholder: "مثلاً آماده برای QA",
    actionSaved: "عملیات ذخیره شد",
    actionDeleted: "عملیات ذخیره‌شده حذف شد",
    useAction: "استفاده از عملیات",
    deleteAction: "حذف عملیات",
    selectIssuesFirst: "اول تسک‌های Jira را انتخاب کن",
    selectedActionReady: "عملیات ذخیره‌شده بارگذاری شد. قبل از اعمال آن را بررسی کن.",
    boardOverview: "نمای کلی بورد",
    activeSprintIssues: "اسپرینت فعال",
    backlogIssues: "بک‌لاگ",
    unassignedIssues: "بدون مسئول",
    unestimatedIssues: "بدون استیمیت",
    lastCreated: "آخرین ساخته‌شده‌ها",
    quickActions: "دسترسی سریع",
    openManager: "باز کردن مدیریت Jira",
    openQuickIssue: "ساخت تسک سریع",
    openImport: "ورود گروهی",
    openReview: "مرور پیش‌نویس",
    refreshWorkspace: "تازه‌سازی فضای کار",
    optional: "اختیاری",
} as const
