export const copyENB = {
    sprint: "Sprint",
    backlog: "Backlog",
    placement: "Placement",
    priority: "Priority",
    defaultPriority: "Default priority",
    defaultSprint: "Default sprint",
    assignee: "Assignee",
    defaultAssignee: "Default assignee",
    labels: "Labels",
    defaultLabels: "Default labels",
    type: "Issue type",
    summary: "Summary",
    description: "Description",
    epic: "Epic",
    ref: "Reference",
    addAttachment: "Add images or files",
    attachmentHelp: "Files are uploaded to Jira after the issue is created. Local selections are not stored in JSON.",
    attachmentDrop: "Drop images or files here, or click to browse",
    attachmentDropActive: "Drop to attach",
    attachmentTypes: "PNG, JPG, WEBP, PDF, WEBM, TXT, LOG, JSON · max 12 MB each",
    richHelp: "Jira wiki formatting",
    createIssue: "Create issue",
    addToBatch: "Add to batch",
    createBatch: "Create in Jira",
    createSelected: "Create selected",
    validate: "Validate",
    dryRun: "Dry run",
    reviewIssues: "Review issues",
    jsonEditor: "JSON editor",
    rawJson: "Raw JSON",
    jsonValid: "Valid JSON",
    jsonInvalid: "Invalid JSON",
    sampleJson: "Download example JSON",
    uploadJson: "Upload JSON",
    aiTemplate: "Copy AI prompt",
    copied: "Copied",
    resetSample: "Reset sample",
    searchIssues: "Search issues…",
    filter: "Filter",
    allTypes: "All types",
    allPlacements: "All placements",
    sprintOnly: "Sprint",
    backlogOnly: "Backlog",
    moveSelected: "Move selected…",
    settings: "Appearance & layout",
    sidebarSettings: "Settings",
    sidebarProjects: "Projects",
    helpSupport: "Help & support",
    clearForm: "Clear form",
    emptyLaneHint: "Issues you move here will appear instantly.",
    batchSettings: "Batch settings",
    change: "Change",
    issueDetails: "Issue details",
    noIssueSelected: "Select an issue to edit it.",
    noIssues: "No issues match the current filters.",
    emptyLane: "No issues in this lane",
    selected: "selected",
    selectAll: "Select all",
    clearSelection: "Clear selection",
    sendBacklog: "Send selected to Backlog",
    duplicate: "Duplicate",
    delete: "Delete",
    inherited: "Batch default",
    useDefault: "Use batch default",
    noDefault: "No default",
    noEpic: "No epic",
    active: "Active",
    future: "Future",
    projectSearch: "Search projects…",
    projectEmpty: "No matching projects.",
    epicSearch: "Search batch or Jira epics…",
    epicEmpty: "No matching epics.",
    batchEpic: "Batch",
    jiraEpic: "Jira",
    labelSearch: "Search or create a label…",
    labelEmpty: "No matching labels. Type a label and press Enter to create it.",
    loadingLabels: "Loading Jira labels…",
    createLabel: "Create label",
    assigneeSearch: "Search assignable users…",
    assigneeEmpty: "No assignable users found.",
    unassigned: "Unassigned",
    importReady: "JSON is ready to review.",
    errors: "errors",
    warnings: "warnings",
    issues: "issues",
    runResults: "Run results",
    retryFailed: "Retry failed creates",
    retrySprint: "Retry sprint placement",
    created: "created",
    failed: "failed",
    attachmentsFailed: "attachment upload failed",
    noResults: "Nothing has been created in Jira yet.",
    confirmCreateTitle: "Create these issues in Jira?",
    confirmCreateDescription: "Only the selected issues will be created. Required local Epics are included automatically.",
    confirmCreate: "Create now",
    cancel: "Cancel",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    language: "Language",
    accent: "Accent color",
    layout: "Review layout",
    grid: "Grid",
    list: "List",
    boardView: "Board",
    columns: "Grid columns",
    density: "Density",
    compact: "Compact",
    comfortable: "Comfortable",
    spacious: "Spacious",
    done: "Done",
    context: "Jira context",
    autoSprint: "Active sprint selected automatically.",
    noSprint: "No active/future sprint found. New issues will stay in Backlog unless changed.",
    quickSuccess: "Issue created successfully.",
    quickFailure: "Issue creation failed.",
    imported: "Imported",
    downloadPrompt: "Download AI prompt",
    viewIssue: "View in Jira",
    createCount: "Create {count} issues",
    workspace: "Workspace",
    workspaceTitle: "QueueMint workspace",
    workspaceHint: "See the board at a glance, jump into work, and reuse your safest Jira actions.",
    commandPalette: "Command palette",
    commandPaletteHint: "Jump to a screen or run a workspace action.",
    commandSearch: "Search commands, screens, and actions…",
    commandEmpty: "No matching command.",
    openCommandPalette: "Open command palette",
    savedActions: "Saved actions",
    savedActionsHint: "Save a bulk-edit setup once and reuse it on future selections.",
    noSavedActions: "No saved actions yet. Configure a bulk edit and save it here.",
    saveAction: "Save as action",
    actionName: "Action name",
    actionNamePlaceholder: "e.g. Ready for QA",
    actionSaved: "Saved action created",
    actionDeleted: "Saved action deleted",
    useAction: "Use action",
    deleteAction: "Delete action",
    selectIssuesFirst: "Select Jira issues first",
    selectedActionReady: "Saved action loaded. Review it before applying.",
    boardOverview: "Board overview",
    activeSprintIssues: "Active sprint",
    backlogIssues: "Backlog",
    unassignedIssues: "Unassigned",
    unestimatedIssues: "No estimate",
    lastCreated: "Last created",
    quickActions: "Quick actions",
    openManager: "Open Jira manager",
    openQuickIssue: "Create quick issue",
    openImport: "Import batch",
    openReview: "Review draft",
    refreshWorkspace: "Refresh workspace",
    optional: "optional",
} as const
